### PR TITLE
[Android-10] Telephony: Do not instantiate PhoneStateListener with subId

### LINKED ISSUE #463: [Q] [Ganges] SIM card doesnt work
**Platform:** Ganges
**Device:** Mermaid
**Kernel version:** 4.9.185
**Android version:** 10
**Software binaries version:** latest

**Description**
When launching android 10 i get the option to enter passcode for SIM but when i do the dialog dissapears but SIM card doesnt work even after that.

**How to reproduce**
Boot android and enter sim code.

**Additional context**
At this point im unable to provide logcat or dmesg as i had to switch back to 9 as i need to receive calls.
Only thing i can share are system, vendor, boot, userdata images.

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/463

subId has been dropped from the constructor, and will later be removed
from the PhoneStateListener class entirerly. Instead, the listener
should be registered through a TelephonyManager for that specific subId.
See:
https://android.googlesource.com/platform/frameworks/base/+/84a90870aa021fa168fab4db613fb87f8d58a4c1
for the relevant change that throws an InvalidArgumentException when
trying to instantiate the class with a subId.

Note that this requires the TelephonyManager to stay around for
deregistration, since it is responsible for carrying the number since Q.
For that reason, it has been stuffed with the PhoneStateListenerImpl
even though that's not the nicest design choice. See the relevant
listen() method here:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r2/telephony/java/android/telephony/TelephonyManager.java#5025

This should be compatible with Pie, where the subId is also stored in
TelephonyManager, and used as default when PhoneStateListener is created
with the default constructor:
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-9.0.0_r48/telephony/java/android/telephony/TelephonyManager.java#4212

Tagging @jzoran for review.

Tested on Discovery (SS) @ Android 9;
Mermaid (DSDS) + Akatsuki (DSDS) @ Android 10.
All with a single sim.

### TODO:
- [ ] Test this on a DSDS device _with two sims inserted_.

### CODE REVIEW

**Comment by stefanhh0** [comment]
Tested this PR on Android 10r1 on Yoshino/Lilac using kernel 4.9.189-gf407e2b59108. 
Did a test-call to another phone everything seems to be fine in that constellation.

File: common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java [hunk 1]
```diff
@@ -108,8 +106,15 @@ public static boolean isDataActive(@NonNull final Context context)
 
     // for each SIM:
     private final class PhoneStateListenerImpl extends PhoneStateListener {
-        PhoneStateListenerImpl(int subId) {
-            super(subId);
+        // Keep track of the used manager for deregistration purposes.
+        private final TelephonyManager mTelephonyManager;
+
+        PhoneStateListenerImpl(TelephonyManager manager) {
```
Comment (jzoran) [inline common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java:112]: super();
While the default constructor gets inserted automatically, changes in PhoneStateListener constructors may add unnecessary issues. Always better to be explicit.

Comment (MarijnS95) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java:112]: Good one!

(See, Java is not my forte...)

Comment (MarijnS95) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java:112]: Though, now that think about it some more, I don't see an obvious reason why.

If the parameterless constructor disappears, this will fail compilation _anyway_. Do you have an example where this prevents said "unnecessary issues"?

File: common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java [hunk 2]
```diff
@@ -108,8 +106,15 @@ public static boolean isDataActive(@NonNull final Context context)
...
+            mTelephonyManager = manager;
+        }
+
+        TelephonyManager getManager() {
```
Comment (jzoran) [inline common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java]: Instead of exposing the TelephonyManager write a listen method, e.g. something like:
`public void listen(int events) {
     mTelephonyManager.listen(this, events);
 }`

and then call `listener.listen(event)` instead of  `listener.getManager().listen (listener, event)` below.

Comment (MarijnS95) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java]: Yep, that's what I intended to do but didn't want to place `mTelephonyManager` there in the first place. If you think that's allright we can insert a `listen` method.

**Review by jzoran — CHANGES_REQUESTED** [review]
Mostly lgtm. Minor changes left.

Also, do you want to add your name/nick and email to AUTHORS file for attribution?

File: common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java (hunk 1 above)
Comment (jzoran) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java:112]: I'd rather the compilation fails for an obvious reason, hence the explicit call.

File: common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java (hunk 2 above)
Comment (jzoran) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java]: It's fine for this purpose.

File: common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java (hunk 1 above)
Comment (MarijnS95) [reply common/src/com/sony/transmitpower/observer/TelephonyStateObserver.java:112]: Allright, let's do it.

I checked this in a random android app project, and the error is the same for both cases (invalid number of arguments). However, the inline error squiglies make it more obvious. Without `super()` it reports `There is no default constructor available in Foo`, and with `super()` it reports `Foo(int) in Foo cannot be applied to ()`. The latter is more vague in my opinion, as it sounds more like a lambda function that is applied to a tuple of arguments.
But whatever, that doesn't matter in this case :grin:

**Comment by MarijnS95** [comment]
> Also, do you want to add your name/nick and email to AUTHORS file for attribution?

I don't really mind, it's a very minor contribution.

Btw, what do you want to do with `mSubId` in the debug prints? This is scheduled for removal and there is no public access to it in `Telephonymanager` (`getSubId` is private).
We can remove it or store the ID in `PhoneStateListenerImpl`.

Force-pushed the code with the requested changes. Note that **this is not compile-tested yet**; I do not have access to my build machine at the moment.

**Comment by jzoran** [comment]
Let's leave the `mSubId` in logs. It's annotated with `@UnsupportedAppUsage` so it might stay for a while. I found it useful during implementation for testing. We'll see how useful it is in the future.

**Comment by jzoran** [comment]
> > Also, do you want to add your name/nick and email to AUTHORS file for attribution?
> 
> I don't really mind, it's a very minor contribution.

Every contribution matters. ;-)

> Force-pushed the code with the requested changes. Note that **this is not compile-tested yet**; I do not have access to my build machine at the moment.

Ok. I'll merge when you can build/test.

**Comment by MarijnS95** [comment]
> Every contribution matters. ;-)

Hehe, well as long as we are not going to add an `AUTHORS` file to every sonyxperiadev repository, I prefer reading the contributors from the git log :wink: 

> Ok. I'll merge when you can build/test.

Tested, compiles and works fine :)
Have you been able to verify this with a DSDS device with second sim inserted?
